default_platform(:ios)

platform :ios do
  desc "Assign testflight groups"
  lane :assign_groups do
    app_store_connect_api_key(
      key_id: "54GDX3ZRZU",
      issuer_id: "8da56372-26b9-474a-a426-c691338169a5",
      key_filepath: File.expand_path("~/.private_keys/AuthKey_54GDX3ZRZU.p8")
    )
    pilot(
      app_identifier: "com.gragera.lumen",
      app_platform: "ios",
      ipa: "/Users/gragera/code/antigravity/lumen/Lumen/build/Lumen.ipa",
      groups: ["Internal Testers", "Dev Team"],
      distribute_external: false,
      skip_submission: true,
      wait_for_uploaded_build: true
    )
  end
end
