devices([
  "iPhone 16 Pro Max",
  "iPhone SE (3rd generation)"
])

languages([
  "en-US"
])

scheme("Lumen")
workspace("Lumen.xcworkspace")
output_directory("./screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
reinstall_app(true)
erase_simulator(true)

skip_testing([
  "LumenTests"
])
