default_platform(:ios)

platform :ios do
  private_lane :api_key do
    app_store_connect_api_key(
      key_id: "54GDX3ZRZU",
      issuer_id: "8da56372-26b9-474a-a426-c691338169a5",
      key_filepath: File.expand_path("~/.private_keys/AuthKey_54GDX3ZRZU.p8")
    )
  end

  desc "Build and upload app to TestFlight"
  lane :upload_testflight do
    api_key

    build_app(
      scheme: "Lumen",
      configuration: "Release",
      destination: "generic/platform=iOS",
      export_options: "./ExportOptions.plist",
      xcargs: "-allowProvisioningUpdates"
    )

    pilot(
      skip_waiting_for_build_processing: false,
      skip_submission: false,
      groups: ["Internal Testers", "Dev Team"]
    )
  end

  desc "Assign testflight groups"
  lane :assign_groups do
    api_key
    pilot(
      app_identifier: "com.gragera.lumen",
      app_platform: "ios",
      groups: ["Internal Testers", "Dev Team"],
      distribute_only: true,
      build_number: "11"
    )
  end

  desc "Upload metadata to App Store Connect"
  lane :upload_metadata do
    api_key
    deliver(
      app_identifier: "com.gragera.lumen",
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end

  desc "Submit app for review"
  lane :submit_for_review do
    api_key
    deliver(
      app_identifier: "com.gragera.lumen",
      skip_binary_upload: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: false,
      force: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end
